[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | .venv
  | .__pycache__
  | _build
  | buck-out
  | build
  | dist
)/
'''