name: Pylint Lint Check

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          source venv/bin/activate
          pylint **/*.py
